### ISSUE TITLE
[Feature]: Enable Advanced Logger in PEI and MM on Q35 and SBSA

### ISSUE THREAD

**Issue by TaylorBeebe** [microsoft/mu_tiano_platforms#522]
### Feature Overview

Advanced Logger is enabled in DXE on Q35 and SBSA, and it should be enabled in all phases.

### Solution Overview

Add PEIM, PEI_CORE, MM_CORE, and MM_STANDALONE instances of AdvancedLoggerLib and the Advanced Logger DebugLib.

### Urgency

Low

### Are you going to implement the feature request?

I will implement the feature

### Do you need maintainer feedback?

No maintainer feedback needed

**Comment by TaylorBeebe** [comment]
The following PR fulfills this request: https://github.com/microsoft/mu_tiano_platforms/pull/801

**Comment by kuqin12** [comment]
> The following PR fulfills this request: #801

The #801 will not be able to cover MM_CORE and MM_STANDALONE due to the fact that current advanced logger implementation is relying on the memory buffer to be initialized from TFA, which will require further customization.

The modification of TFA for broader usage needs separate planning. We will discuss this internally before any public movement here.
